version: "3.9"

services:
  mariadb:
    image: mariadb:11
    container_name: tfg-mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: tfg_db
      MARIADB_USER: tfg_user
      MARIADB_PASSWORD: tfg_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
